include: package:flutter_lints/flutter.yaml

linter:
  rules:
    unawaited_futures: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint
