// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5a6p7YZhAu-TK0SzhUY7KPd_DgLxVEdI',
    appId: '1:145740451737:web:a339176dba0be1a45c0d08',
    messagingSenderId: '145740451737',
    projectId: 'greendao-a5344',
    authDomain: 'greendao-a5344.firebaseapp.com',
    storageBucket: 'greendao-a5344.appspot.com',
    measurementId: 'G-Y2QRTBDCRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Ir0abgf4qP8n2TyfQxWHlMic0ASDpu8',
    appId: '1:145740451737:android:af6ef58fabd4130e5c0d08',
    messagingSenderId: '145740451737',
    projectId: 'greendao-a5344',
    storageBucket: 'greendao-a5344.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpXbILblFiINuyeEbVCzS4_btByeYovwo',
    appId: '1:145740451737:ios:6136db1e2e41e5e15c0d08',
    messagingSenderId: '145740451737',
    projectId: 'greendao-a5344',
    storageBucket: 'greendao-a5344.appspot.com',
    iosClientId: '145740451737-tafc94jm6k7o75bpkih3gdjvjo79qrem.apps.googleusercontent.com',
    iosBundleId: 'com.susipero.greendayo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpXbILblFiINuyeEbVCzS4_btByeYovwo',
    appId: '1:145740451737:ios:6136db1e2e41e5e15c0d08',
    messagingSenderId: '145740451737',
    projectId: 'greendao-a5344',
    storageBucket: 'greendao-a5344.appspot.com',
    iosClientId: '145740451737-tafc94jm6k7o75bpkih3gdjvjo79qrem.apps.googleusercontent.com',
    iosBundleId: 'com.susipero.greendayo',
  );
}
